POST  http://127.0.0.1:8000/auth/signup/
Content-Type: application/json

{
    "username": "Sergioooo",
    "password":"Pass1234!",
    "email": "a@gmail.com"
}

###

POST  http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "username": "Sergiooo",
    "password":"Pass1234!"
}
###
POST  http://127.0.0.1:8000/auth/profile/
Content-Type: application/json

{
    "username": "alamorre",
    "password":"Pass1234!"
}

###
GET  http://127.0.0.1:8000/users/signup/
Content-Type: application/json

{
    "username": "Sergio",
    "password":"Pass1234!",
    "email": "a@gmail.com"
}