# Generated by Django 5.1.5 on 2025-03-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor_data_dist',
            old_name='valDiferncia',
            new_name='valDiferencia',
        ),
    ]
