# Generated by Django 5.1.5 on 2025-04-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_rename_valdiferncia_sensor_data_dist_valdiferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_data_dist',
            name='sensor',
        ),
    ]
