# Generated by Django 5.1.5 on 2025-04-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_remove_sensor_data_dist_sensor'),
        ('sensors', '0002_piezometro_delete_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data_dist',
            name='sensor_piezometro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.piezometro'),
        ),
    ]
