# Generated by Django 5.1.5 on 2025-04-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0004_sensor_data_dist_sensor_piezometro'),
        ('sensors', '0002_piezometro_delete_sensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor_data_dist',
            new_name='Sensor_data_piezometro',
        ),
    ]
