# Generated by Django 5.1.5 on 2025-04-23 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0005_rename_sensor_data_dist_sensor_data_piezometro'),
        ('sensors', '0003_inclinometro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_data_inclinometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('valActual', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('valDiferencia', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('sensor_inclinometro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.inclinometro')),
            ],
        ),
    ]
