# Generated by Django 5.1.5 on 2025-04-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('sensor_data', '0003_remove_sensor_data_dist_sensor'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piezometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('coord', models.JSONField(blank=True, null=True)),
                ('cotaZ', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('cotaInicial', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
