# Generated by Django 5.1.5 on 2025-04-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('sensors', '0002_piezometro_delete_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclinometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('coord', models.JSONField(blank=True, null=True)),
                ('cota', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('cotaI', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
