# Generated by Django 5.1.5 on 2025-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensor_project_sensor_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='coord',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
